CREATE TABLE app_user (
    id VARCHAR(255) PRIMARY KEY,
    username VARCHAR(128) NOT NULL,
    name VARCHAR(255),
    surname VARCHAR(255),
    email VARCHAR(255),
    mod_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
